### ISSUE TITLE
Suggestion: Add support for general assembly

### ISSUE THREAD

**Issue by DevynCJohnson** [AndiDittrich/EnlighterJS#12]
I noticed that EnlighterJS supports AVR-Assembly. I would like to suggest that assembly for the 8051 or general assembly syntax be added to EnlighterJS (unless the "avrasm" shortcode in the WordPress plugin already covers that).

By the way, I know JavaScript. How could I contribute by adding support for various programming languages?

**Comment by AndiDittrich** [comment]
Dear Devyn,
is there any general language-reference (keywords, commands) available for assembly code ? 
i thought it is platform/compiler depending ?

To develope language "addons" for EnlighterJS you can take a look into the following files 

* **Source/Language/Template.mylang.js** (Demo Language implentation used as entry point)
* **LanguageDevelopment.phtml** (General Language Development Environment, requires a local webserver)

best regards, Andi

**Comment by DevynCJohnson** [comment]
There are some forms of assembly that use different syntax and commands. However, 8051 assembly is used by numerous devices (mostly embedded), and many related forms of assembly use most of the same commands. Here is the instruction set and syntax - https://en.wikipedia.org/wiki/Intel_MCS-51#Instruction_set

Thanks for the info. By the way, I thought EnlighterJS supported HTML, but I am not seeing the file in https://github.com/AndiDittrich/EnlighterJS/tree/master/Source/Language . I am wanting to add MathML to the HTML template (MathML is included in the W3C HTML5 standard).

**Comment by DevynCJohnson** [comment]
By the way, if I added support for Cython (an implementation of Python), should I make it its own file or in the Python file since Cython and Python share most of the same keywords?

**Comment by AndiDittrich** [comment]
The HTML language is an alias for XML. But im currently working on EnlighterJS v3 which includes a new tokenizer engine with major (incompatible changes) which means that especally the XML/HTML language will change completely.

in case a language is a superset of another you should create a own file which extends the origin language. For example https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Language/Less.js

**Comment by DevynCJohnson** [comment]
Okay, thank you for the help and info. I look forward to adding additional language support

**Comment by AndiDittrich** [comment]
i've just added general assembly language support as well as some avr assembly improvements. 
feel free to try it out.

**Comment by DevynCJohnson** [comment]
Excellent! I look forward to seeing this in the next WordPress plugin update.
