### ISSUE TITLE
Suggestion: Further CSS Optimization

### ISSUE THREAD

**Issue by DevynCJohnson** [AndiDittrich/EnlighterJS#17]
I was looking at https://raw.githubusercontent.com/AndiDittrich/EnlighterJS/master/Build/EnlighterJS.min.css and I ran the code through http://csscompressor.com/ . Then, I saw that you already compressed and optimized the code as much as it can be optimized. However, I do see one possible improvement that you may want to consider.

Is there an easy way (or would it be a good idea) to allow WordPress users to select which themes to enable/disable and then only use the needed CSS code? In other words, if a user disabled the "Twilight" theme, then the "Twilight" classes would not be in the CSS file that is loaded by WordPress.

## Background Info

./Build/EnlighterJS.min.css contains CSS classes for each of the themes supported by EnlighterJS. Obviously, the WordPress plugin (which I use on DCJTech.info) allows a user/poster to select a theme. However, on my website, I reduced the size of the plugin's files by deleting the themes I did not want users/posters to use. Thus, I could remove the CSS classes for themes my website does not use.

One reason why I offer this as a mere suggestion is because I do not know how you feel about "nit-picky" optimizations. On my website, I use many micro-optimizations. True, one micro-optimization may not contribute much performance improvement, but many micro-optimizations on a website that is visited by hundreds of people per day adds up quickly and yields significant results.

**Comment by AndiDittrich** [comment]
Thank's for your suggestion.
Such feature is scheduled for the next major release of the WordPress plugin. I have to implement a lot of improvements and optimization. therefore it will not be added to the current release.

but for your use-case i would recommend you to include the Enlighter-Themes into your global theme and disable the "default" themes. i use the same method within my blog. this allows you to add a several optimizations.

**Comment by DevynCJohnson** [comment]
Thanks for your feedback. Yes, on my website, I edited some of EnlighterJS's code and moved all of the CSS to my theme's CSS file.
