### ISSUE TITLE
Question: LanguageDevelopment.phtml

### ISSUE THREAD

**Issue by DevynCJohnson** [AndiDittrich/EnlighterJS#18]
I am looking over some of EnlighterJS's code and I noticed the ./LanguageDevelopment.phtml file ( https://github.com/AndiDittrich/EnlighterJS/blob/master/LanguageDevelopment.phtml ). Unless I am mistaken, ./LanguageDevelopment.phtml does not contain any PHP code, so why is the file using the extension "*.phtml"? Such a file extension is used for HTML files that contain PHP code ( http://stackoverflow.com/questions/11859015/what-is-phtml-and-when-should-i-use-a-phtml-extension-rather-than-php ). Should ./LanguageDevelopment.phtml use the "*.html" file-extension, or did I over-look soemthing?

By the way, if you would rather me offer these suggestions and question via email, please feel free to let me know. Using GitHub's "Issues" or email are equally convenient for me. I can use which ever would be the best for you.

**Comment by AndiDittrich** [comment]
you're right. PHP is not needed anymore for these files (ThemeDevelopment.html and LanguageDevelopment.html). i've changed their file extensions to `.html`
