### ISSUE TITLE
Wild Suggestion: Open-Source Biology Highlighting

### ISSUE THREAD

**Issue by DevynCJohnson** [AndiDittrich/EnlighterJS#19]
This idea may be off-topic or very different from EnlighterJS's main purpose of high-lighting computer code. As you may have seen in the news, scientists have discovered how to make boolean logic gates using biochemicals (i.e. DNA, RNA, proteins, etc.). For instance, Boolean Integrase Logic (BIL) gates are DNA and RNA transistors (*DNA and RNA transistors = transcriptors*), and DNA and RNA are coded using four nucleic acids ("A", "C", "G", and "T"). What if EnlighterJS gained supported for "biochemical computer code"?

On my website, there is a page that could benefit from such a feature - http://dcjtech.info/topic/open-source-biology-logic-gates/

**WARNING:** My website has ads. Some people feel that the ads are annoying and some people get more upset if I do not give them a note of warning, so I want to warn you now. (^u^)

Perhaps, the background for each of the four DNA-letter-codes ("A", "C", "G", and "T") could be different rather than coloring the letter itself. Such a color scheme is commonly seen in bioinformatics software. For example, this highlighting scheme can be seen in this image from Wikimedia/Wikipedia - https://upload.wikimedia.org/wikipedia/commons/a/a7/WPP_domain_alignment.PNG

If such a feature is added, I would be happy to help or add the code myself. I have a one-year college degree in biology, so I am familiar with these biochemistry topics. Also, if highlighting support is added for nucleic acids (DNA and RNA), then it would be wise to add support for amino acid highlighting (for protein-based computer component source-code). In addition, this Wikipedia article ( https://en.wikipedia.org/wiki/FASTA_format ) may assist us in adding such a feature.

**Comment by AndiDittrich** [comment]
Maybe - but formats like FASTA are quite difficult to highlight

**Comment by DevynCJohnson** [comment]
True. However, the highlighting that I am proposing is not for the actual FASTA format. Instead, I am proposing that EnlighterJS users could use a "dna" WordPress-shortcode enclosing a DNA sequence (i.e. "ATCGATCG") and the background of each letter be highlighted.
