### ISSUE TITLE
The following code between [java] tags breaks from wordpress.

### ISSUE THREAD

**Issue by dgerenrot** [AndiDittrich/EnlighterJS#20]
When I try to use [java] tags from wordpress editor, the following code breaks the plugin:

------------------------- BEGIN

public ObjectArrayDump loadObjectArrayDump(InputStream is)
	throws IOException {

	ObjectArrayDump objectArrayDump = new ObjectArrayDump();
	HProfId id = loadId(is);
	byte[] uIntBytes = new byte[Long.SIZE];

	// Bad
	// is.read(uIntBytes, 4, SIZE_U4);

	// Better
	// is.read(uIntBytes, Long.SIZE - SIZE_U4, SIZE_U4);

	// Best
	is.read(uIntBytes, uIntBytes.length - SIZE_U4, SIZE_U4);

	long stackTraceSerialNo = ByteBuffer.wrap(uIntBytes).asLongBuffer().get();

	is.read(uIntBytes, uIntBytes.length - SIZE_U4, SIZE_U4);
	long numArrayEntries = ByteBuffer.wrap(uIntBytes).asLongBuffer().get();

	objectArrayDump.setId(id);
	objectArrayDump.setNumArrayEntries(numArrayEntries);

	HProfId[] objectIds = new HProfId[(int)numArrayEntries];

	// Bad
	// for (int i = 0; i < numArrayEntries; i++) {

	// Good
	for (int i = 0; i < objectIds.length; i++) {
		objectIds[i] = loadId(is);
	}

	return objectArrayDump;
}

-------------------------------- END

**Comment by AndiDittrich** [comment]
Dear Dmitry,

thanks for your report. 

I've tried your example in visual editor mode and it worked as expected, as well as using the Enlighter "Code Insert" button. I can reproduce the issue in "Text Mode"

In "Text Mode" you have to take care of html-special-chars by yourself. in your example there are some enclosing brackets like `<` and `>` which cause the WordPress internal shortcode handler to ignore the shortcode. 
by escaping them, everything is working fine within my development environment:

```
public ObjectArrayDump loadObjectArrayDump(InputStream is)
throws IOException {

ObjectArrayDump objectArrayDump = new ObjectArrayDump();
HProfId id = loadId(is);
byte[] uIntBytes = new byte[Long.SIZE];

// Bad
// is.read(uIntBytes, 4, SIZE_U4);

// Better
// is.read(uIntBytes, Long.SIZE - SIZE_U4, SIZE_U4);

// Best
is.read(uIntBytes, uIntBytes.length - SIZE_U4, SIZE_U4);

long stackTraceSerialNo = ByteBuffer.wrap(uIntBytes).asLongBuffer().get();

is.read(uIntBytes, uIntBytes.length - SIZE_U4, SIZE_U4);
long numArrayEntries = ByteBuffer.wrap(uIntBytes).asLongBuffer().get();

objectArrayDump.setId(id);
objectArrayDump.setNumArrayEntries(numArrayEntries);

HProfId[] objectIds = new HProfId[(int)numArrayEntries];

// Bad
// for (int i = 0; i &lt; numArrayEntries; i++) {

// Good
for (int i = 0; i &lt; objectIds.length; i++) {
objectIds[i] = loadId(is);
}

return objectArrayDump;

}
```

**Comment by AndiDittrich** [comment]
I've added a new, fault-tolerant Shortcode Handler to the Enlighter plugin to avoid such issues in the future. It's available within the current [master branch](https://github.com/AndiDittrich/WordPress.Enlighter) (v2.12-BETA4)

**Comment by dgerenrot** [comment]
Thank you!
