### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by PixelT** [AndiDittrich/EnlighterJS#22]
Add sass / scss language

**Comment by AndiDittrich** [comment]
SASS / SCSS / LESS language support is projected for EnlighterJS v3

**Comment by AndiDittrich** [comment]
First of 3 - [LESS](http://lesscss.org/) support is ready :)

![enlighter_less](https://cloud.githubusercontent.com/assets/1474107/16076793/7bf3a3c8-32f5-11e6-8c02-4f6d08ba73a5.jpg)

**Comment by AndiDittrich** [comment]
Second one - [SCSS](http://sass-lang.com/guide)

![enlighter_scss](https://cloud.githubusercontent.com/assets/1474107/16077708/c4396730-32fa-11e6-95a9-29a254f1b794.jpg)

@PixelT as i know, SASS v3 prefers the SCSS syntax which is (like LESS) a superset of CSS - do you think it is enough to support this version ?
