### ISSUE TITLE
Blurred blocks with wordpress

### ISSUE THREAD

**Issue by maxouille** [AndiDittrich/EnlighterJS#30]
Hi ! 

The plugin work but my blocks are blurred ... Do you know why ? 

![2017-10-06 18_25_50-maxence bobin python keyboard interrupt handling with multiprocessing](https://user-images.githubusercontent.com/5927407/31288092-d80d14fe-aac3-11e7-9cc8-a0546a7dea5d.png)

Thx !

**Comment by AndiDittrich** [comment]
hi maxouille ,
it looks like a missing fontfile or some 3rd party text effects.

did you tried another theme ?

if you like you can post a link to an example page. this allows me to investigate the issue :)

br, Andi

**Comment by maxouille** [comment]
I tried another theme. And I installed the plugin via the wordpress plugin interface. 

http://bobin.iiens.net/python-keyboard-interrupt-handling-with-multiprocessing/ 

This is the page when it happens :)

**Comment by AndiDittrich** [comment]
hi,
the issue is caused by your WordPress Themes CSS :

file: `dark.css`, rule: **text-shadow**

```
body {
    background: #000 url(../images/body-bg1.png) repeat 0 0;
    color: #999999;
    text-shadow: 1px 1px #000000;
}
```

**Comment by maxouille** [comment]
So I need to remove this rule ?

**Comment by AndiDittrich** [comment]
you can remove it or explicit override it for the enlighter codeblocks:

```css
.EnlighterJS, .EnlighterJSWrapper{
   text-shadow: none !important;
}
```

:)

**Comment by maxouille** [comment]
I tried to add this to the dar.css and it does not work. 

It does not work either when I add it to the enlighter.css :(
