### ISSUE TITLE
Making long rows not to break?

### ISSUE THREAD

**Issue by egantz** [AndiDittrich/EnlighterJS#31]
Hi! I was curious how can I force long lines to stay the same without wrapping words?

I see that if I set a width to the inner ul element long lines will remain as they are without break. Read through the Docs and couldn't find an official solution for this. help?

Instead of this:
<img width="721" alt="screen shot 2017-12-31 at 7 04 52 pm" src="https://user-images.githubusercontent.com/4982233/34464781-89459066-ee5d-11e7-8b2a-c0dbc6785125.png">

I want it to look like this:
<img width="759" alt="screen shot 2017-12-31 at 7 05 51 pm" src="https://user-images.githubusercontent.com/4982233/34464784-a942d8a6-ee5d-11e7-9e96-3fb33749e482.png">

So the user can just scroll horizontally if the lines are longer than the container.

**Comment by AndiDittrich** [comment]
of course, see https://github.com/AndiDittrich/WordPress.Enlighter/issues/31

**Comment by egantz** [comment]
Thanks! :)
