### ISSUE TITLE
Enlighter 2.6 - Bug with email address code

### ISSUE THREAD

**Issue by sf32738** [AndiDittrich/EnlighterJS#6]
Example code view:

<pre class="EnlighterJSRAW" data-enlighter-language="null">$CONF['admin_email'] = 'sysadmin@example.tld';</pre>

Output on rendered page includes the javascript code block after the close of the pre tag.
(Screenshots attached).

![enlighter 2 6_bug_screen1](https://cloud.githubusercontent.com/assets/9754218/7775620/ad6c9488-0082-11e5-80a4-5632a3fa03ce.png)
![enlighter 2 6_bug_screen2](https://cloud.githubusercontent.com/assets/9754218/7775622/b080dca6-0082-11e5-99c3-f06f88c87dc4.png)

**Comment by sf32738** [comment]
I should mention that this is using the WordPress plugin --- sorry about that.

**Comment by AndiDittrich** [comment]
Dear Flynn,

following your screenshots, the javascript code which is injected behind the E-Mail Address ist **not** EnlighterJS related. The code is injected by another plugin/software you're using (cf-email).

The problem is caused by you CloudFlare EMail Protection service: http://stackoverflow.com/questions/27513190/cf-hash-attribute-and-script-mysteriously-added-to-mailto-links

Maybe you can exclude special pages from CloudFlare or may use an EMail Protection Plugin like [Cryptex](https://wordpress.org/plugins/cryptex/) within WordPress directly.

best regards, Andi

**Comment by sf32738** [comment]
Thank you Andi --- I didn't even think to check that!

**Comment by sf32738** [comment]
This is confirmed to be the case.  For anyone else that happens across this, here is the setting in CloudFlare that would require changing.

![cf_email_address](https://cloud.githubusercontent.com/assets/9754218/7778437/57d7670c-0099-11e5-8a99-fa7a054666c8.png)

Problem is now resolved.

![cf_email_address_fixed](https://cloud.githubusercontent.com/assets/9754218/7778440/5b211034-0099-11e5-803d-f12cecc468de.png)

**Comment by AndiDittrich** [comment]
Great Tipp! CloudFlare just replied on my [Tweet](https://twitter.com/andidittrich/status/601836965445656576) and they consider using PageRules to exclude special pages from E-Mail Objuscation

**Comment by sf32738** [comment]
PageRules may be an option, but on a site that is being used as a KB system, that could end up being a lot of special pages to exclude.  I am going to test your Cryptex plugin as well to see if that gets around the issue with CloudFlare.

**Comment by sf32738** [comment]
It appears the Cryptex plugin does not play nice with the EnlighterJS plugin.  When the tag is applied to the inside of the EnlighterJS code block, it bugs out.  But when applied by itself (to confirm it was working and not something I did wrong on the server setup) it works fine.

![image](https://cloud.githubusercontent.com/assets/9754218/7779004/9ab24d30-009e-11e5-84d8-3075e1d23718.png)

![image](https://cloud.githubusercontent.com/assets/9754218/7779012/adec5abc-009e-11e5-881b-bfa06123643c.png)

**Comment by AndiDittrich** [comment]
When using Cryptex together with Syntax-Highlighters you should disable the autodetection feature and use shortcodes only - this will avoid such issues.

**Comment by sf32738** [comment]
I did confirm that it was disabled prior to reply.

![image](https://cloud.githubusercontent.com/assets/9754218/7779065/396ff4ae-009f-11e5-92be-5085ce42e54a.png)

**Comment by AndiDittrich** [comment]
Well, it cannot work to use obfuscated addresses within the highlighting.

**Comment by AndiDittrich** [comment]
Dear Flynn,

I've just release EnlighterJS 2.6.0, Enlighter v2.7 as well as Cryptex 5.0 - now they will work together after a long weekend :)

best regards, Andi

**Comment by sf32738** [comment]
Andi --- Very cool!   Sorry you worked all weekend on this, as there wasn't any rush to fix it.  Again, thank you though...  I will download the new versions and test it out on my WP install.
