### ISSUE TITLE
Rust Support

### ISSUE THREAD

**Issue by brandonio21** [AndiDittrich/EnlighterJS#7]
EnlighterJS syntax highlighting support for Rust. [rust-lang](http://rust-lang.org)

**Comment by AndiDittrich** [comment]
Dear brandon,

thank's for your feature request. i've just created a Rust language support file following the official reference.
can you please check the demo if something is missing ?

http://enlighterjs.andidittrich.de/Rust_Demo.html

best regards, Andi

**Comment by brandonio21** [comment]
Wow. And here I was forking the project and working on my own Rust support using the official reference. The demo looks great!

**Comment by AndiDittrich** [comment]
Here are the current js sources, maybe you can use them and add the missing parts: http://enlighterjs.andidittrich.de/Source/Language/Rust.js
