### ISSUE TITLE
Double "</script>" output in JS language

### ISSUE THREAD

**Issue by Kalydon** [AndiDittrich/EnlighterJS#8]
Hi,

with v2.7.0, when attempting to highlight JS code that is also enclosed in the "`<script type="text/javascript">`" and "`</script>`" lines, Enlighter is outputting the "`</script>`" part twice at the end. While those two lines are of course not technically JS code (but usually included), v2.6.0 of Enlighter could render it just fine. This would be a sample code that causes the issue:

    <script type="text/javascript">
		window.addEvent('domready', function() {
			// highlight all pre tags
			$('pre').light({
				altLines : 'hover',
				indent : 2,
				editable: false
			});
		});
    </script>

Kalydon

**Comment by AndiDittrich** [comment]
Dear Kalydon,
thanks for your feedback, i can confirm the issue. 
I've replaced the complete tokenizer&rendering engine in the last release and will take a look on what's going wrong.

best regards, Andi

**Comment by AndiDittrich** [comment]
the fix will be included within the next release. it's a bug within the new tokenizer (missing exit condition)

**Comment by Kalydon** [comment]
Andi,

that sounds great! Any idea when the next release will happen? If the release is still some time away, could you provide the fix here in this topic already, since highlighting JS code is fairly important for my usage.

Thank you!

Kalydon

**Comment by AndiDittrich** [comment]
the release will follow in the next few hours

**Comment by Kalydon** [comment]
Andi,

that's just awesome! thanks for such a quick fix!

Kalydon

**Comment by AndiDittrich** [comment]
v2.8.0 is out including the bugfix!
