### ISSUE TITLE
May you help me? How to remove this HightLight Section  ?

### ISSUE THREAD

**Issue by XMap** [AndiDittrich/EnlighterJS#9]
Use this ?  It just could be hide .
```
 document.getElements('pre').enlight(false);
```

And remove #div.EnlighterJSWrapper# ?

It can't hightlight again ...   :-(

**Comment by XMap** [comment]
I wanna remove it  , Because When I execute it many times. It will  show highlight section many times.

**Comment by AndiDittrich** [comment]
Dear XMap,

For performance reasons the enlight(false) call will only toggle the container visibility (EnlighterJSWrapper is set to invisible, you pre container visible again).

In case you remove the DOM it cannot be highlighted again - you have to create a new EnlighterJS instance. 

Best regards, Andi

**Comment by XMap** [comment]
En,  I'm know that  ...  but why this framework use this MooTools .Does it conflict with jQuery  or Angulr?

**Comment by AndiDittrich** [comment]
You can use MooTools together with jQuery. But you should take of the the script include priority: http://mootools.net/blog/2009/06/22/the-dollar-safe-mode

**Comment by AndiDittrich** [comment]
i've added an additional `dispose()` function to the EnlighterJS class which will destroy all generated DOM Elements and restores the original state (unhighligted code).

**Element Style**
```js
// remove highlighting (drop generated HTML from DOM)
document.id('myHighlightedCode').enlight('dispose');
```

**OOP Style**
```js
// create a new EnlighterJS instance
var myEnlighter = new EnlighterJS(document.id('myCustomCode'), {
  language: 'php',
  showLinenumbers: false
});

// enable highlighting
myEnlighter.enlight(true);

// remove highlighting (drop generated HTML from DOM)
myEnlighter.dispose();
```

**Comment by gclove** [comment]
:thumbsup:
